### ISSUE TITLE
Failed to verify email

### ISSUE THREAD

**Issue by s4msy** [john-overton/yet-another-wiki#8]
Hi,

i just want to try your wiki, and fired it up with this compose file:
```yaml
services:
  app:
    image: joverton/yet-another-wiki-app:1.0.016
    ports:
      - 3000:3000
    volumes:
      - ./data:/data
      - ./db:/db
      - ./config:/config
      - ./public:/public
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=https://my.domain.com
      - DATABASE_URL=file:../db/yetanotherwiki.db
    restart: unless-stopped
networks: {}
```

This ends up with the setup Page, but every mail-address isn't verified. Any chance there is an Environment variable for deactivating the mail address verfication?
